theme: jekyll-theme-minimal
title: Supernova Hunters
description: Pages for tracking discoveries from the Supernova Hunters citizen science project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://SupernovaHunters.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SNHuntersPS1
github_username: SupernovaHunters


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
